### ISSUE TITLE
[Main & Beta Branch/Search] Searching doesn't seem to work for me.

### ISSUE THREAD

**Issue by Lannuked** [ciulinuwu/cosmic-cat#65]
1. Describe the bug:
Searching doesn't seem to work.
![image](https://user-images.githubusercontent.com/26724236/185783197-44427927-be2e-45b2-850f-c846ffa93440.png)
2. Screenshot of Developer Tools Console (Must have Logs, Warn, Error, Debug & Info enabled):
![image](https://user-images.githubusercontent.com/26724236/185783119-6d015e59-1ea7-4165-bfbe-46b2653a94e5.png)
![image](https://user-images.githubusercontent.com/26724236/185783123-f1b28373-41d8-4c04-90ae-0c37d0e50f63.png)
3. Page URL of where you encountered the issue:
https://www.youtube.com/results?search_query=funny+cats
4. Browser:
Firefox Nightly 105.0a1

**Comment by ciulinuwu** [comment]
Hi. Thank you for your report. Does this occur on another searches as well?

**Comment by Lannuked** [comment]
Every search is the same deal.

**Comment by Lannuked** [comment]
I think I might know the problem, _**maybe**_. The userscript usually takes about a second to load on every youtube link I click. It causes a bit of lag, and I'm thinking it's some kind of race condition (if I'm using the correct term here) between the page loading and the script loading.

After a bit of testing, it seems to sometimes work, but I should probably show you the lag I'm experiencing.
![firefox_CPC4rvIliu](https://user-images.githubusercontent.com/26724236/185799259-1bc665de-c68b-4b8d-b303-de5d5a7b2fc8.gif)

**Comment by ciulinuwu** [comment]
Hi @Lannuked. Can you test 0.5.43 and see if it's still occurring?

**Comment by Lannuked** [comment]
![image](https://user-images.githubusercontent.com/26724236/187338306-b9f77081-f327-4d88-bc42-07ce83ff3f6a.png)
![image](https://user-images.githubusercontent.com/26724236/187338408-9daeba15-9afa-419f-86cb-79506a2a7f7e.png)
![firefox_bpDdRwWGnL](https://user-images.githubusercontent.com/26724236/187339010-979a1ab1-6180-4f5f-bbe2-1873ce607194.gif)
![image](https://user-images.githubusercontent.com/26724236/187338240-dc39ae67-b18e-43db-bc24-177302e89ee8.png)

Not really

**Comment by ciulinuwu** [comment]
Hi @Lannuked. Can you test Beta 3 and see if the issue still occurs?

https://github.com/ciulinuwu/cosmic-cat/raw/beta/cosmic-cat.user.js

**Comment by Lannuked** [comment]
Loading does seem to be a lot smoother and less jumpy as it tries to load all the assets, but searching seems to give me a blank page when it fails now. After a few refreshes most searches seem to go through, though.

**Comment by Lannuked** [comment]
Actually, I think that might have been cache, as searching seems to be working 90% of the time, and the search I was trying to do was an old search that didn't work.

**Comment by Lannuked** [comment]
Odd, some searches bring up a blank page, this is confusing me.

**Comment by ciulinuwu** [comment]
Hi @Lannuked, can you check if Beta 5.1 fixes this issue?

**Comment by Lannuked** [comment]
That appears to have done the trick, it seems. Everything is a lot cleaner when loading, and searching appears to work every time after some brief testing. I wish you luck with this project, and I hope to see this get a lot more recognition.
