### ISSUE TITLE
[Main Branch/Comments] Multi-Line Comments are not properly displayed

### ISSUE THREAD

**Issue by micenest** [ciulinuwu/cosmic-cat#70]
1. Describe the bug:
When you use the regular YouTube layout, typically you would have certain comments that make usage of Multi Lines. However, in Cosmic Cat, only the first comment line is actually displayed.

Comment in Regular Youtube:
![image](https://user-images.githubusercontent.com/56133320/187264190-240dac30-5b52-4815-be24-7c5c1f6a75bc.png)

Comment using Cosmic Cat:
![image](https://user-images.githubusercontent.com/56133320/187264328-39f9f958-af9e-44c6-893d-51f0a75ada08.png)

2. Page URL of where you encountered the issue: /watch
3. Browser: Firefox version 103.0, Running under Cosmic Cat 0.5.43

**Comment by ciulinuwu** [comment]
Thank you for reporting. I will look into it!

**Comment by darkalexis1990** [comment]
> Thank you for reporting. I will look into it!

please check mine also thanks!

https://github.com/ciulinuwu/cosmic-cat/issues/38#issuecomment-1228372884

**Comment by ciulinuwu** [comment]
Hi! I'm already aware of this group of issues. I dunno how to fix all of them at the moment. But hopefully soon!

>

**Comment by ciulinuwu** [comment]
Has been fixed in Beta 5.1.

I will close this once the beta releases.
