### ISSUE TITLE
Important features don't work/are missing

### ISSUE THREAD

**Issue by zeffdakilla** [ciulinuwu/cosmic-cat#73]
1. Describe the bug: I can't seem to find anywhere where notifications are, and adding videos to playlists do not work. When the "Add to" button is pressed, nothing happens. There is also nowhere to view your playlists.
None of the buttons work here either except My channel.
![image](https://user-images.githubusercontent.com/111836537/188262199-57cafc6a-09d7-4da5-9641-363467c7f8ff.png)
Replying to comments also doesn't work and you can't view any replies.
2. Screenshot of Developer Tools Console (Must have Logs, Warn, Error, Debug & Info enabled):
![image](https://user-images.githubusercontent.com/111836537/188262056-621933b2-c615-4830-9411-a84e076ab70f.png)
![image](https://user-images.githubusercontent.com/111836537/188262066-92c41bee-331e-4fb9-b606-7d068e69f0d2.png)
3. Page URL of where you encountered the issue: Home page and every video page
4. Browser: Chrome

**Comment by ciulinuwu** [comment]
Hi! I am already aware that the script is lacking some features. The project is still super WIP and it's also mentioned on the repo main page. I hope you understand now! Also, next time please use this to report actual bugs!
