### ISSUE TITLE
[Main Branch/Player] Fullscreen player bar is way too high

### ISSUE THREAD

**Issue by pankine** [ciulinuwu/cosmic-cat#75]
1. Describe the bug:
When i enter fullscreen mode on any video, the bottom player bar thing is too high which leaves some black pixels, the same issue does not happen to the top bar
2. Screenshot of Developer Tools Console (Must have Logs, Warn, Error, Debug & Info enabled):
3. Page URL of where you encountered the issue:
this happens on every page so
4. Browser:
i am using Librewolf 103.0.2
![image](https://user-images.githubusercontent.com/88506607/188473776-a51bb70d-fa4b-4f9e-b417-61f288b54aa1.png)
![image](https://user-images.githubusercontent.com/88506607/188474272-6bd43686-26a5-4973-880c-1bbf3de19db8.png)

**Comment by ciulinuwu** [comment]
Also recommendation: Don't use multiple YouTube frontend scripts at the same time.

**Comment by pankine** [comment]
> Also recommendation: Don't use multiple YouTube frontend scripts at the same time.

yeah i forgot to disable redux for some reason, gonna do that

**Comment by ciulinuwu** [comment]
Hi! Apologies for the late answer, but this issue has been fixed in our beta.
