### ISSUE TITLE
Channel page not appearing

### ISSUE THREAD

**Issue by SakuHashira** [ciulinuwu/cosmic-cat#77]
bug : channel page not appearing
page url : https://www.youtube.com/channel/UCCZGYab5SpD0I7Z5JqJZgww
browser : google chrome

![Capture d’écran 2022-09-05 224704](https://user-images.githubusercontent.com/112906315/188513527-31829f3b-81f9-47b3-8e35-432293d3d33f.png)

**Comment by ciulinuwu** [comment]
HI! I have noticed you got auto-banned by accident! I have unbanned you and apologize for the inconvenience!

**Comment by ciulinuwu** [comment]
Hi @SakuHashira, can you check Beta 3 and see if channels can load now?

https://github.com/ciulinuwu/cosmic-cat/raw/beta/cosmic-cat.user.js

**Comment by ciulinuwu** [comment]
Closed due to inactivity.

Developer note: This should be fixed in the next beta, hopefully.

**Comment by nottakenusernametotally** [comment]
Just refresh the pages if it dosent work, i never got that problem
