### ISSUE TITLE
watch page won't load

### ISSUE THREAD

**Issue by TheOrbOfDestiny** [ciulinuwu/cosmic-cat#78]
Bug: Watch page won't load
URL: https://www.youtube.com/watch?v=iCkYw3cRwLo (also happens on other videos)
Browser: Firefox (latest version)
![report 2](https://user-images.githubusercontent.com/90469208/188900384-3a2ae780-daf1-4aa6-acd0-22e751f35af1.png)

**Comment by evil-scout** [comment]
Having the same issue. Did youtube change something that broke this in an update? Was working fine a few days ago.

**Comment by ciulinuwu** [comment]
Hi. It works fine for me.

However, YouTube might've rolled out an update for specific users.

I need to see all console messages. Can you please screenshot all of them?

**Comment by ciulinuwu** [comment]
Inactive.

Author failed to provide requested information.
