### ISSUE TITLE
[i18n] "Loading" does not display correctly on current Beta

### ISSUE THREAD

**Issue by asfasdfasdfsdsdf** [ciulinuwu/cosmic-cat#82]
### Type

Page Renderer

### Page URL

All pages

### Branch

beta

### Version

Newest one

### A brief description

I just saw this when i'm subed to channels it shows nothing instead of "subscribed" and when i unsubscribe it shows [object Object] and same on when you press on your channel icon in header it shows [object Object] same on channel page

### Screenshots or videos

![Screenshot 2022-09-27 at 18-45-20 I Made Two Solar Systems Collide and This Happened - Universe Sandbox 2 - YouTube](https://user-images.githubusercontent.com/106913603/192574175-8f681c75-2ce0-4349-973a-b80c5c385a2e.png)

### Console output

Idk what to type i'm lazy to show but atleast i can tell

**Comment by asfasdfasdfsdsdf** [comment]
same on browse it shows [object Object] like dude

**Comment by ciulinuwu** [comment]
This is due to i18n having changed for an up-coming update.

**Comment by ciulinuwu** [comment]
Hi! The beta has now released. The text should work now!

https://github.com/ciulinuwu/cosmic-cat/raw/beta/cosmic-cat.user.js
