### ISSUE TITLE
[OLD] The watch page doesn't load

### ISSUE THREAD

**Issue by BenjaminMakesGarbage** [ciulinuwu/cosmic-cat#83]
### Type

Page Renderer

### Page URL

https://www.youtube.com/watch?

### Branch

main

### Version

v0.5.43

### A brief description

I was able to play videos with this before, but now when I click on a video, it just shows a blank white screen.

### Screenshots or videos

![Screenshot 2022-09-28 145452](https://user-images.githubusercontent.com/103474921/192876372-5cebe4dc-22a2-4be4-a485-1e84b81b0a78.png)

### Console output

I don't know what a console output is.

**Comment by ciulinuwu** [comment]
Hello, thank you for reporting this.

I am already aware of the issue and have fixed this in Beta.
You can get the beta from here: https://github.com/ciulinuwu/cosmic-cat/raw/beta/cosmic-cat.user.js

**Comment by BenjaminMakesGarbage** [comment]
> Hello, thank you for reporting this.
> 
> I am already aware of the issue and have fixed this in Beta. You can get the beta from here: https://github.com/ciulinuwu/cosmic-cat/raw/beta/cosmic-cat.user.js

the beta version's player is very zoomed in and the controls are missing

**Comment by ciulinuwu** [comment]
Hi! Can you show me how it's zoomed in?

**Comment by BenjaminMakesGarbage** [comment]
![Screenshot 2022-09-29 123955](https://user-images.githubusercontent.com/103474921/193103685-56cda995-c302-4f88-896d-fed9903c659c.png)

**Comment by ciulinuwu** [comment]
Ah. That's weird. It might be because of the player being incomplete. Can you right click on the player and see if it makes an image cover the entire page?

**Comment by blingakinga32** [comment]
> Ah. That's weird. It might be because of the player being incomplete. Can you right click on the player and see if it makes an image cover the entire page?

I installed the beta on both chrome and opera gx and I found both have this issue, also i'm not sure why but the "add to", "share", and "subscribe" buttons are all blank text for me. The player is also invisible for me when hovering over a video, and whenever load a page you can't scroll and it plays two versions of the same video at the same time. I found installing Iridium allows you to scroll the page and pause one version of the video in the player, but the second version still plays in the background. I'll send a video sometime later if you need me to.

**Comment by blingakinga32** [comment]
Here's of screenshot of what it looks like for me:

![Screenshot 2022-09-30 063236](https://user-images.githubusercontent.com/114742013/193260802-295fa2db-fee6-4af5-8f58-ede6f48c18bf.png)

**Comment by blingakinga32** [comment]
> About the missing text, it's due to a lot of internal rewrite mainly on Ciulinations (i18n) and pageRenderer for the next beta.
> 
> 
> 
> Do you have an Adblocker? If not, I have a theory that the ads "might" be breaking the player.

Yes, I tried both enabling and disabling ublock on both browsers and both have the issue of the page freezing and duplicate videos.

**Comment by ciulinuwu** [comment]
Hmm.. Have you tried with Firefox?

**Comment by blingakinga32** [comment]
> Hmm.. Have you tried with Firefox?

Just tried it with firefox instead of opera and chrome and all of the issues i mentioned above were pretty much solved, so these problems seem to only be on chrome-based browsers. Going to start using Waterfox instead so I can use the firefox version of this extension with my chrome extensions, too.

**Comment by ciulinuwu** [comment]
Glad to hear it works on Firefox!

I will look into why the player is broken on Chrome.

**Comment by blingakinga32** [comment]
> Hi. I believe the issue might be fixed now in Beta 7.
> 
> However I released the beta because self-testing was inconsistent and I needed user input. So I don't know if it is 100% working? But hopefully tho!

Hi, I tested the new beta in firefox and the only issue with the player is that videos don't play on their own and you have to manually go pause/unpause the video for it to start. Using the beta on chrome is kinda hard to use and weird though, you can very rarely get some videos to play correctly with the player working and everything but you have to refresh the page a LOT of times (I found using "reopen closed tab" makes it more likely for the player controls to show up):
![asf](https://user-images.githubusercontent.com/114742013/193384185-fe628b01-2ac9-431c-ba76-a4c9b2b6a00a.png)
However, most of the time when you click on a video it will bring you to a page that looks like this: 
![2](https://user-images.githubusercontent.com/114742013/193384063-62ae690b-bcef-4b16-91d3-12dcab563512.png)
Refreshing the page will bring you to a page that either looks like this:
![alt page](https://user-images.githubusercontent.com/114742013/193384079-35fcac84-63b6-498f-971c-824f11a72432.png)
or this:
![page](https://user-images.githubusercontent.com/114742013/193384330-781be722-61a5-4697-8f88-3b4514678b36.png)

Here are some other bugs and issues I found, (not as important, just letting you know):
- There is an issue I think with videos that were originally premiered or live not playing and giving an error occured screen.
- The "featured" section of a channel does not work on any channels.
- The only section that works in the picture below is the "my channel" section, "browse channels" also doesn't do anything.
![channel2](https://user-images.githubusercontent.com/114742013/193386009-2e570ee0-ae7f-4a39-8c16-1241c8d61264.png)
- "view" button currently doesn't do anything and I think it would look nicer if the text matched the color of the "uploads" text.
![playlists](https://user-images.githubusercontent.com/114742013/193385665-2b24ef9f-1a4c-474d-86de-913aaf46ae62.png)
- most channels have a "undefined" subscriber count
- hovering over a video shows a white circle in the top right corner
![hover2](https://user-images.githubusercontent.com/114742013/193385983-7f5130b3-a997-4662-baad-456e666e8a31.png)
- these sections don't work and for some reason there is a "d" category
![browse](https://user-images.githubusercontent.com/114742013/193386671-479a7687-dab5-4fac-a80c-bb846948d269.png)
![section](https://user-images.githubusercontent.com/114742013/193386682-69cc152e-f50e-4dd8-9814-edce29bc0268.png)
![categories](https://user-images.githubusercontent.com/114742013/193386743-3d54e383-d9a2-419c-9884-995596af3142.png)

**Comment by Skittleology** [comment]
> > Hi. I believe the issue might be fixed now in Beta 7.
> > However I released the beta because self-testing was inconsistent and I needed user input. So I don't know if it is 100% working? But hopefully tho!
> 
> Hi, I tested the new beta in firefox and the only issue with the player is that videos don't play on their own and you have to manually go pause/unpause the video for it to start. Using the beta on chrome is kinda hard to use and weird though, you can very rarely get some videos to play correctly with the player working and everything but you have to refresh the page a LOT of times (I found using "reopen closed tab" makes it more likely for the player controls to show up): ![asf](https://user-images.githubusercontent.com/114742013/193384185-fe628b01-2ac9-431c-ba76-a4c9b2b6a00a.png) However, most of the time when you click on a video it will bring you to a page that looks like this: ![2](https://user-images.githubusercontent.com/114742013/193384063-62ae690b-bcef-4b16-91d3-12dcab563512.png) Refreshing the page will bring you to a page that either looks like this: ![alt page](https://user-images.githubusercontent.com/114742013/193384079-35fcac84-63b6-498f-971c-824f11a72432.png) or the "duplicate videos playing at the same time" issue will happen again and the video in the player will start zoomed in, which you can fix by pausing the video in fullscreen and then pressing escape: ![page](https://user-images.githubusercontent.com/114742013/193384330-781be722-61a5-4697-8f88-3b4514678b36.png)
> 
> Here are some other bugs and issues I found, (not as important, just letting you know):
> 
> * There is an issue I think with videos that were originally premiered or live not playing and giving an error occured screen.
> * The "featured" section of a channel does not work on any channels.
> * The only section that works in the picture below is the "my channel" section, "browse channels" also doesn't do anything.
>   ![channel2](https://user-images.githubusercontent.com/114742013/193386009-2e570ee0-ae7f-4a39-8c16-1241c8d61264.png)
> * "view" button currently doesn't do anything and I think it would look nicer if the text matched the color of the "uploads" text.
>   ![playlists](https://user-images.githubusercontent.com/114742013/193385665-2b24ef9f-1a4c-474d-86de-913aaf46ae62.png)
> * most channels have a "undefined" subscriber count
> * hovering over a video shows a white circle in the top right corner
>   ![hover2](https://user-images.githubusercontent.com/114742013/193385983-7f5130b3-a997-4662-baad-456e666e8a31.png)
> * these sections don't work and for some reason there is a "d" category
>   ![browse](https://user-images.githubusercontent.com/114742013/193386671-479a7687-dab5-4fac-a80c-bb846948d269.png)
>   ![section](https://user-images.githubusercontent.com/114742013/193386682-69cc152e-f50e-4dd8-9814-edce29bc0268.png)
>   ![categories](https://user-images.githubusercontent.com/114742013/193386743-3d54e383-d9a2-419c-9884-995596af3142.png)

Can confirm I have the same issue.

**Comment by Skittleology** [comment]
Can confirm I have the same issue as blingakinga in beta 6 hotfix 1.

**Comment by ciulinuwu** [comment]
> > Hi. I believe the issue might be fixed now in Beta 7.
> > However I released the beta because self-testing was inconsistent and I needed user input. So I don't know if it is 100% working? But hopefully tho!
> 
> Hi, I tested the new beta in firefox and the only issue with the player is that videos don't play on their own and you have to manually go pause/unpause the video for it to start. Using the beta on chrome is kinda hard to use and weird though, you can very rarely get some videos to play correctly with the player working and everything but you have to refresh the page a LOT of times (I found using "reopen closed tab" makes it more likely for the player controls to show up): ![asf](https://user-images.githubusercontent.com/114742013/193384185-fe628b01-2ac9-431c-ba76-a4c9b2b6a00a.png) However, most of the time when you click on a video it will bring you to a page that looks like this: ![2](https://user-images.githubusercontent.com/114742013/193384063-62ae690b-bcef-4b16-91d3-12dcab563512.png) Refreshing the page will bring you to a page that either looks like this: ![alt page](https://user-images.githubusercontent.com/114742013/193384079-35fcac84-63b6-498f-971c-824f11a72432.png) or the "duplicate videos playing at the same time" issue will happen again and the video in the player will start zoomed in, which you can fix by pausing the video in fullscreen and then pressing escape: ![page](https://user-images.githubusercontent.com/114742013/193384330-781be722-61a5-4697-8f88-3b4514678b36.png)
> 
> Here are some other bugs and issues I found, (not as important, just letting you know):
> 
>     * There is an issue I think with videos that were originally premiered or live not playing and giving an error occured screen.
> 
>     * The "featured" section of a channel does not work on any channels.
> 
>     * The only section that works in the picture below is the "my channel" section, "browse channels" also doesn't do anything.
>       ![channel2](https://user-images.githubusercontent.com/114742013/193386009-2e570ee0-ae7f-4a39-8c16-1241c8d61264.png)
> 
>     * "view" button currently doesn't do anything and I think it would look nicer if the text matched the color of the "uploads" text.
>       ![playlists](https://user-images.githubusercontent.com/114742013/193385665-2b24ef9f-1a4c-474d-86de-913aaf46ae62.png)
> 
>     * most channels have a "undefined" subscriber count
> 
>     * hovering over a video shows a white circle in the top right corner
>       ![hover2](https://user-images.githubusercontent.com/114742013/193385983-7f5130b3-a997-4662-baad-456e666e8a31.png)
> 
>     * these sections don't work and for some reason there is a "d" category
>       ![browse](https://user-images.githubusercontent.com/114742013/193386671-479a7687-dab5-4fac-a80c-bb846948d269.png)
>       ![section](https://user-images.githubusercontent.com/114742013/193386682-69cc152e-f50e-4dd8-9814-edce29bc0268.png)
>       ![categories](https://user-images.githubusercontent.com/114742013/193386743-3d54e383-d9a2-419c-9884-995596af3142.png)

Thank you for reporting this issue!

* About the player, I'll see if I can prevent it from automatically starting!

* Due to Chrome's lack of support for "beforescriptexecute" it's a bit difficult preventing polymer's files from loading, but I'll try to fix this.

* The code I use to delay Cosmic Cat's code execution until the script tag containing "ytInitialData" appears isn't the best because it's inconsistent. So I don't know how to fix that right now

* "d" is a left over from me testing out Ciulinations, and in the upcoming beta has been replaced with "<no i18n string>"
