### ISSUE TITLE
[Old] Channels do not load.

### ISSUE THREAD

**Issue by thoudankeykang** [ciulinuwu/cosmic-cat#84]
### Type

Page Renderer

### Page URL

https://www.youtube.com/channel/*

### Branch

main

### Version

0.5.43

### A brief description

Most channel pages do not load

### Screenshots or videos

![image](https://user-images.githubusercontent.com/89052168/192924391-6dd723b1-a524-4071-b23b-ec56b09c2356.png)

### Console output

[www.youtube.com-1664418303091.log](https://github.com/ciulinuwu/cosmic-cat/files/9670324/www.youtube.com-1664418303091.log)

**Comment by ciulinuwu** [comment]
Hi! Thank you for reporting.

Channels 2.0 is currently being phased out in favor of 3.0. 

Grab the latest beta here and it should be working, however this beta does have a few issues regarding loading pages `/` and `/watch` specifically. But ye! 

https://github.com/ciulinuwu/cosmic-cat/raw/beta/cosmic-cat.user.js
