### ISSUE TITLE
Subscriber count not showing

### ISSUE THREAD

**Issue by asfasdfasdfsdsdf** [ciulinuwu/cosmic-cat#85]
### Type

Page Renderer

### Page URL

All channel pages

### Branch

beta

### Version

hotfix bruh

### A brief description

on all channel pages it's showing "undefined subscribers" like dude it's something like bugged or whatever and also if i wasted your time it's not my reason. and maybe it's just on my browser showing.

### Screenshots or videos

i won't show it because you can see this bug normally

### Console output

Storage.init {"storageVer":20221001122800,"lang":"en","dark":"0","i18n":{"language":"en","author":"","json": {"global":{"browse":"Browse","upload":"Upload","help":"Help","about":"About","copyright":"Copyright","advertising": "Advertising","loading":{"main":"Loading...","comment":"Loading comment","suggestions":"Loading more suggestions..."},"channel":"Channel" ,"seeall":"see all","search":"Search","browsechannels":"Browse channels","press":"Press & Blogs","creators":"Creators & Partners"},"playlists ":{"header":{"channelAuthor":"by %s"},"body":{"primaryPane":{"items":{"video":{"by":"by %s"}} },"secondaryPane":{"aboutSection":{"about":"About %s","creatorLinks":{"playlists":"%s playlists by %r","videos":"View all videos"} }}}},"channels":{"creatorBar":{"analytics":"Analytics","videomanager":"Video Manager","settings":"Channel Settings"},"header":{"stats" :{"subscriber":"subscriber","subscribers":"subscribers","videoview":"video view","videoviews":"video views"},"tabs":{"featured":"Featured", "vi deos":"Browse videos","search":"Search Channel"}},"body":{"secondaryPane":{"userProfile":{"about":"About %s","createdBy":{" by":"by %s"}}}}},"search":{"playlists":{"by":"by %s"}},"stats":{"likesdislikes":"%s likes, %r dislikes"},"buttons":{"watch":{"showmore":"Show more","showless":"Show less","like":"Like","dislike":"Dislike", "addto":"Add to","share":"Share"},"subscribe":{"subscribe":"Subscribe","subscribed":"Subscribed","unsubscribe":"Unsubscribe"},"suggestions ":{"loadmoresuggestions":"Load more suggestions"},"comments":{"post":"Post"},"showmore":"Show more","showless":"Show less","signin": "Sign In"},"suggestions":{"loading":"Loading more suggestions..."},"tooltip":{"watch":{"ilikethis":"I like this","idislikethis":" I dislike this","addto":"Add to favorites or playlist","share":"Share or embed this video","flag":"Flag as inappropriate","statistics":"Show video statistics"," clicktobe":"Click to be notified of new videos from this channel","transcript":"Interactive Transcript"}},"watch" :{"watchInfo":{"category":"Category:","tags":"Tags:","license":"License:"},"comments":{"charactersremain":"%s characters remaining" ,"secondsremain":"%s seconds remaining before you can post","loading":"Loading comment...","allcomments":"All Comments","topcomments":"Top Comments","respond": "Respond to this video..."},"tags":"Tags","license":"License","uploaderinfo":"Uploaded by %s on %r","category":"Category"," from":"From: %s","by":"by %s"},"home":{"feed":{"uploadedavideo":"%s uploaded a video","islive":"%s is live"}},"uploadmonth":{"jan":"Jan","feb":"Feb","mar":"Mar","apr":"Apr","may":"May" ,"jun":"Jun","jul":"Jul","aug":"Aug","sep":"Sep","oct":"Oct","nov":"Nov"," dec":"Dec"},"about":{"country":"Country:","membersince":"Joined:","viewedcounts":"Views:","viewedcount":"View:"," sub":"Subscriber:","subs":"Subscribers:"},"customtag":{"age":"Age:","occupation":"Occupation:"},"personal":{"mychannel" :"My channel","videos":"Videos","likes":"Likes","history":"History","watchlater":"Watch Later","v ideomanager":"Video Manager","youtubesettings":"YouTube settings","subscriptions":"Subscriptions","profile":"Profile","privacy":"Privacy","settings":"Settings"," signout":"Sign out","switchaccount":"Switch account","googleaccount":"Google account"},"browse":{"mostviewed":"Most Viewed Today","recommended":"Recommended for You "},"guide":{"fromyt":"From YouTube","trending":"Trending","popular":"Popular","music":"Music","live":"Live"," gadgets":"Gaming","news":"News","sports":"Sports","education":"Education","howto":"Howto & Style"}}},"i18n.setup": "1"} Cosmic Cat.user.js:3917:21
Storage.init has init. Cosmic Cat.user.js:3922:21
This page uses the non-standard "zoom" property. Try using calc() on the appropriate property values, or use "transform" along with "transform-origin: 0 0". eval:2253:26
Some cookies incorrectly use the recommended "SameSite" attribute 14
toggleElm toggled .header-stats Cosmic Cat.user.js:2177:17
toggleElm toggled #feed-loading-template Cosmic Cat.user.js:2177:17
a Cosmic Cat.user.js:388:13
The resource "https://i.ytimg.com/generate_204", already downloaded from the preload link, has not been used for several seconds. Make sure all attributes of the "preload" tag have been set correctly. videos
Uncaught TypeError: c.initKeyEvent is not a function
    https://s.ytimg.com/yts/jsbin/www-searchbox-vflOEotgN.js:15
    K https://s.ytimg.com/yts/jsbin/www-searchbox-vflOEotgN.js:62
    f https://s.ytimg.com/yts/jsbin/www-searchbox-vflOEotgN.js:32
    d https://s.ytimg.com/yts/jsbin/www-searchbox-vflOEotgN.js:33
    v https://s.ytimg.com/yts/jsbin/www-searchbox-vflOEotgN.js:114
    a https://s.ytimg.com/yts/jsbin/www-searchbox-vflOEotgN.js:122
www-searchbox-vflOEotgN.js:15:384
Uncaught TypeError: c.initKeyEvent is not a function
    https://s.ytimg.com/yts/jsbin/www-searchbox-vflOEotgN.js:15
    K https://s.ytimg.com/yts/jsbin/www-searchbox-vflOEotgN.js:62
    f https://s.ytimg.com/yts/jsbin
    /www-searchbox-vflOEotgN.js:32
     d https://s.ytimg.com/yts/jsbin/www-searchbox-vflOEotgN.js:33
     v https://s.ytimg.com/yts/jsbin/www-searchbox-vflOEotgN.js:114
     a https://s.ytimg.com/yts/jsbin/www-searchbox-vflOEotgN.js:122
42 www-searchbox-vflOEotgN.js:15:384

**Comment by ciulinuwu** [comment]
Hello, thank you for reporting.

I am already aware of this issue and this will be fixed in the next update!
