### ISSUE TITLE
YouTube Player 

### ISSUE THREAD

**Issue by KSPortalcraftmods** [ciulinuwu/cosmic-cat#93]
### Type

Player

### Page URL

https://www.youtube.com/watch?time_continue=122&v=fEv1ILJS1bE&embeds_euri=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DfEv1ILJS1bE&embeds_origin=https%3A%2F%2Fwww.youtube.com&source_ve_path=Mjg2NjM&feature=emb_logo

### Branch

main

### Version

0.67

### A brief description

I went to watch a video and I saw the new youtube player.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/65189871/213946119-9b3c7506-d7db-4601-9ccd-7b5293696c70.png)

### Console output

none

**Comment by ciulinuwu** [comment]
You can toggle the iFrame player under [settings](https://youtube.com/cosmic_cat).
